version: "3.7"
services:
    api:
        build: .
        ports:
            - "3000:3000"
        environment: 
            - NODE_ENV=production
            - MONGO_URI=mongodb://mongo:27017
            - MONGO_DB=swamphacks
        depends_on: 
            - mongo
    mongo:
        image: mongo
        ports:
        - "27017:27017"